name: PR Merge Comment

on:
  pull_request:
    types: [closed]

permissions: write-all

jobs:
  comment-on-merge:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Count merged PRs
        id: count-prs
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const author = context.payload.pull_request.user.login;
            const repo = context.repo.repo;
            const owner = context.repo.owner;
            
            console.log(`Fetching PR author: ${author}`);
            console.log(`Repository: ${owner}/${repo}`);
            
            const { data } = await github.rest.search.issuesAndPullRequests({
              q: `repo:${owner}/${repo} type:pr state:closed author:${author}`
            });
            const prCount = data.items.filter(pr => pr.pull_request.merged_at).length;
            
            console.log(`PR Count: ${prCount}`);
            
            core.setOutput('pr_count', prCount);
            core.setOutput('author', author);

      - name: Comment on the PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prCount = parseInt(core.getInput('pr_count'));
            const author = core.getInput('author');
            const mention = '@HardikGoyal2003';
            const prNumber = context.payload.pull_request.number;
            
            console.log(`PR Count: ${prCount}`);
            
            let message;
            if (prCount === 1) {
              message = `@${author} 1 PR merged successfully! ${mention}`;
            } else if (prCount === 2) {
              message = `@${author} You have merged 2 PRs successfully! ${mention}`;
            } else {
              message = `Excellent! @${author} You have merged ${prCount} PRs! ${mention}`;
            }
            
            console.log(`Message: ${message}`);
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: message
            });
            
            console.log(`Comment posted successfully on PR #${prNumber}`);
